security:
  oauth2:
    client:
      clientId: 1051340063671-p6dukg2ivkrhpmrf6pr8p8iif1dbkh2n.apps.googleusercontent.com
      clientSecret: HWmV_nfRITq5gHKQja2n2-2x
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientAuthenticationScheme: form
      scope:
        - openid
        - email
        - profile
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: true
      
      
      
      